version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      ZEBRUNNER_RERUN_CONTEXT: "<< pipeline.parameters.rerun-context >>"

    steps:
      - run: echo "Image tag used was ${ZEBRUNNER_RERUN_CONTEXT}"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test

parameters:
  rerun-context:
    default: ""
    type: string
